flatpak/flatpak-github-actions

flatpak-builder/dist/index.js
flatpak-builder/index.js

When the `cache-key` is `undefined` the action falls back to a
default string. However `core.getInput()` returns an empty string
if an option is missing, not `undefined`.
Fix this by doing a falsey check instead of an equality check.

fix default cache-key

---

flatpak-builder/index.js

Store the modified manifest in another JSON or YML file in the same folder of the original file, but prefixed with `flatpak-github-action-modified-`.
Fixes https://github.com/bilelmoussaoui/flatpak-github-actions/issues/61

Don't modify original Flatpak manifest

---

README.md
flatpak-builder/index.js

flatpak-builder: Add 'mirror-screenshots-url' input

---

flatpak-builder/action.yml

This was an oversight of the previous commits.

flatpak-builder: List mirror-screenshots-url in action.yml

---

README.md
flat-manager/action.yml
flat-manager/dist/index.js
flat-manager/index.js
flatpak-builder/action.yml

Related to https://github.com/elementary/appcenter-reviews/issues/293
TL;DR
> There may come a point where an application is no longer maintained. In order to inform users at update or install time that it will no longer get updates.
> 
>If the application has been renamed, you can additionally include end-of-life-rebase with the new ID. Recent flatpak versions will prompt user if they'd like to switch to the renamed app.
Source: https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life

flat-manager: Add 'end-of-life' and 'end-of-life-rebase' inputs

---

README.md

It's not clear this input is actually an override for the
`flatpak-builder` or manifest option of the same name, so state that
explicitly.
Also mention that `--allow=network` and `--allow=x11` are enabled, and
an X11 display is setup by the GitHub Action via `xvfb-run`.
fixes #68

docs: expand documentation for the "run-tests" input

---

README.md

Running tests with the `flatpak-builder` action is fairly simple, but
has some gotchas if you're not familiar with the process.
Add a section with some more explicit examples, detailing what the
developer needs to do to ensure the expected results.
closes #86

docs: add a section with more explicit details about running tests

---

Dockerfile

Install git-lfs alongside other dependencies, since some repositories might need LFS to pull and init correctly.
Closes https://github.com/flatpak/flatpak-github-actions/issues/90

Dockerfile: Install git-lfs

---

README.md

Instead of using the action from Bilal's namespace. The images are still pointing to Bilal's Dockerhub, but that needs porting to GitHub Registry before updating the README.

Update README.md with flatpak/flatpak-github-actions

---

Dockerfile

Since libappstream-glib is no longer a dependency of flatpak in fedora 37, it isn't in the built image. It is useful to be able to run appstream-util to verify metainfo after the flatpak build, so explicitly install libappstream-glib which provides appstream-util.

dockerfile: Add libappstream-glib

---

.github/workflows/flatpak-test.yml
flat-manager/action.yml
flatpak-builder/action.yml

node12 GitHub Actions are now deprecated, and we can port to node16 without any problems.

build: update actions to node16

---

.github/workflows/codespell.yml
.github/workflows/docker.yml
.github/workflows/flatpak-test.yml
CONTRIBUTING.md

This PR basically contains:
- Actions versions update to replace deprecated NodeJS v12 with minimum v16 — the v12 is deprecated and GitHub Actions raises warnings ([example](https://github.com/flatpak/flatpak-github-actions/actions/runs/3722639780))
- CONTRIBUTING.md change with NodeJS v12 bump to v16 for the same reason
- Update runtime image ubuntu-20.04 to ubuntu-22.04 (btw, ubuntu-latest is now ubuntu-22.04)
Some notes:
- Some actions were very out of date, and I was able to successfully test "flatpatk-test.yml" (name: CI), but not "docker.yml" (name: Docker images). So I can't assure it is working just the same with newest action versions, although the syntax and versions are correct and the latest.
- Is elementary-juno image really necessary in docker-image.yml? Their [Continuous …

Update versions in CI

---

Dockerfile

This is practically an undocumented feature of BuildKit, but it avoids making another copy of the script to another layer.
https://github.com/moby/buildkit/pull/1492

Use `ADD --chmod=755`

---

.github/workflows/flatpak-test.yml
README.md
flatpak-builder/action.yml
flatpak-builder/dist/index.js
flatpak-builder/index.js

Rather than modifying the manifest to only build dependencies, @GeorgesStavracas recommended me to use the flatpak-builder `--stop-at=` option by implementing it in the action.
When the option is used, it disables generating the bundle.
This option purpose:
- Build and cache dependencies for long CI run (QEMU aarch64)
- Potentially partial test build

Add a stop-at-module option

---

.github/workflows/flatpak-test.yml
flatpak-builder/dist/index.js
flatpak-builder/index.js

- Moves the code cache key "generation" before calling `prepareBuild()`
- Makes `prepareBuild()` return the cache hit key
- Compares the key and the hit key in `build()` to check if caching is needing (if enabled)
- No more caching error because of an already used key when the given key was hit while restoring.
- Avoid creating a cache on the PR branch while the cache already exist on the default branch (master).
Edit: Sorry for the CI spam.

Avoid caching if key and hit key are identical

---

.github/workflows/flatpak-test.yml
README.md
flatpak-builder/action.yml
flatpak-builder/dist/index.js
flatpak-builder/index.js

I created this option to avoid downloading and restoring a cache that may not help the build at all (e.g. another architecture) and only lose time (depending on cache size and github network speed).
If we check the existence of a cache matching with the cache key or if the manifest was modified beforehand through another workflow step, this option will allow to skip restoring a non-matching cache.

Add a restore-cache option

---

README.md

- Bump versions in workflow examples.
- Change Github to GitHub in some places.
- Center the header, status badge and description to align with the logo. [1]

README: Bump version in examples, minor changes

---

flatpak-builder/index.js

Since `v6`, everything has been being built into the `master` flatpak branch, and the `branch` input from the action configuration is not respected.

Don't override branch input

---

flat-manager/package.json

Fixes #130.
[GitHub Actions has deprecated save-state and set-output](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) and will fully disable them on May 31, 2023. The recommended action is to update `@actions/core` to 1.10.0. While this was already done in flatpak-builder, and it appears to have been done in flat-manager in `flat-manager/yarn.lock`, let's still explicitly set this in `flat-manager/package.json` as well. Also, let's match the values to the values in `flatpak-builder/package.json`.

Bump dependencies

---

flat-manager/dist/index.js
flat-manager/index.js
flatpak-builder/dist/index.js
flatpak-builder/index.js

While unnecessary since all of them have a default value
Having build-bundle set to false was is fact turning it to true through the fallback

Remove boolean options fallback

---

flatpak-builder/dist/index.js
flatpak-builder/index.js

Due to an oversight in [actions/toolkit](https://github.com/actions/toolkit), the `CACHE_PATH` was modified after running `cache.restoreCache` function. As a result, an incorrect version was generated during cache upload, leading to cache missing.
This PR independently passes the `CACHE_PATH` to avoid issues caused by shallow copying.
Fix issue：https://github.com/flatpak/flatpak-github-actions/issues/142
Refer to : https://github.com/actions/toolkit/pull/1378#issuecomment-1478388929

Fix cache missing

---

flatpak-builder/dist/index.js
flatpak-builder/index.js

Currently, the `flatpak-builder` action always assumes the flatpak being built is an application, regardless of whether it is actually a runtime or extension.
Since all runtimes and extensions have a corresponding `build-runtime:`/`build-extension:` property in the manifest, this PR adds the needed `--runtime` flag to `flatpak build-bundle` if either of those are set.

Build runtime bundle if manifest is a runtime or extension

---

flat-manager/action.yml
flatpak-builder/action.yml

Node20 was added to Actions Runner on v2.308.0 and Node16 reaches end of life soon on 11 Sep 2023.
Therefore, This PR updates the default runtime to node20. Sorry I forgot to do it yesterday when bumping `actions/checkout` version.

action: bump runner to node20

---

flat-manager/dist/index.js
flat-manager/index.js

`push_back` is not valid for arrays in JS, so the action was failing when any of the EoL options were set.

fix(flat-manager): Fix push of EoL arguments

---

flat-manager/dist/index.js
flat-manager/index.js

`--verbose` needs to be provided before the command (`create`, `push`, `purge`) and `--end-of-life` is only valid for the `push` stage.

Fix order of verbose and EoL arguments

---

README.md
flatpak-builder/action.yml
flatpak-builder/dist/index.js
flatpak-builder/index.js

About a month ago GitHub made a breaking change to upload-artifact and download-artifact https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/
TLDR artifacts uploaded with v3 can't be downloaded with v4 and vise-versa.
The flatpak-builder automatically uploads the artifact it builds using v3, because it's still using 1.X.X of https://www.npmjs.com/package/@actions/artifact?activeTab=readme and I ran into this pain-point when trying to migrate our CI across the board https://github.com/PCSX2/pcsx2/pull/10431
- these changes were tested there as well https://github.com/PCSX2/pcsx2/blob/7207681485eb2f480ebbc537aac7ec17967aef0d/.github/workflows/linux_build_flatpak.yml#L95
This contribution provides a non-breaking migration path for consumers so they …

builder: add `upload-artifact` flag to skip uploading artifacts

---

README.md

flatpak/flatpak-github-actions/flat-manager should be the latest version in the readme too.
end-of-life does not work with v4, as it was added later. 
On another note: end-of-life is broken on v6 too as it was fixed a couple of days after the latest tag was created (#160) so I had to use @​master to use it.

Update flat-manager to v6 in readme deployment stage

---

.github/workflows/docker.yml
README.md

Freedesktop SDK 24.08 was released today: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/releases/freedesktop-sdk-24.08.0

Add Freedesktop SDK 24.08

---

flatpak-builder/index.js

This maintains the behaviour that flatpak-builder had in the Flathub image but uses the newly introduced argument instead of the downstream patch
See https://github.com/flatpak/flatpak-builder/pull/652
We will need a new v6 tag with this.

Specify full URL policy when mirroring screenshots
